### ISSUE TITLE
 pygdbmi-0.10.0.0 is not compatible

### ISSUE THREAD

**Issue by avicoder** [quarkslab/AERoot#1]
Running ` ./aeroot.py daemon ` is throwing the error.

```
Traceback (most recent call last):
  File "./aeroot.py", line 20, in <module>
    from pygdbmi.constants import GdbTimeoutError
ModuleNotFoundError: No module named 'pygdbmi.constants'
```

which version should I install?

**Comment by Ha0ris** [comment]
Here are the modules installed in my AERoot venv:
~~~
Package         Version   
--------------- ----------
colorama        0.4.4     
pip             20.0.2    
pkg-resources   0.0.0     
pure-python-adb 0.3.0.dev0
pygdbmi         0.10.0.0  
setuptools      44.0.0 
~~~

So you should check your environment.

**Comment by avicoder** [comment]
The issue was with the python version, in the readme it is stated to use `pip` but in actual it is `pip3` already send the pull request with correction.
