### ISSUE TITLE
[macOS] Kernel memory mapping failure at cold boot

### ISSUE THREAD

**Issue by renshuki** [quarkslab/AERoot#33]
**System:**
macOS Mojave (10.14.6)

**Kernel tested:**
- 4.14.112+ x86_64
- 5.4.61-android11-2-00064-g4271ad6e8ade-ab6991359 x86_64

**Emulator version:** 
Android emulator version 30.6.5.0 (build_id 7324830) (CL:N/A)

**Issue description:**
When doing an avd cold boot aeroot fails to map kernel memory.
Loading from a state (snapshot) fix the kernel base address mapping.
Possibly caused by gdbserver/ gdbstub not updating the kernel address mapping properly at boot

**Issue reproduction:**
- Execute `./emulator @AVD_NAME -no-snapshot-load -qemu -s`
- Wait for complete boot of the emulator
- Run `aeroot daemon` (v0.3)

```
AERoot (Android Emulator ROOTing system) v. 0.3
[+] Wait for kernel memory mapping (try: 1/5)...
[+] Wait for kernel memory mapping (try: 2/5)...
[+] Wait for kernel memory mapping (try: 3/5)...
[+] Wait for kernel memory mapping (try: 4/5)...
[+] Wait for kernel memory mapping (try: 5/5)...
[!] Can't retrieve kernel base from memory **Aborting**
[+] Exiting
```

**Workaround**:
- `adb emu avd snapshot save foo`
- `adb emu avd snapshot load foo`
> (to save / load from a snapshot)
- `aeroot daemon`

```
AERoot (Android Emulator ROOTing system) v. 0.3
[+] Kernel base address found at 0xffffffffa7e00000
[+] Process [1784] found at 0xffff9d9eab656040
[+] Overwriting process [1784] credentials
[+] Set SELinux enforce (0xffffffffa929cdc8) to 0
[+] Exiting
```

**Comment by Ha0ris** [comment]
Issue fixed. Thank you. ;)
