### ISSUE TITLE
Emulator console auth token cannot be read with dockerized version

### ISSUE THREAD

**Issue by ilyaglow** [quarkslab/AERoot#47]
Hi,

I noticed that the Dockerized version of AERoot for some AVDs returns `Emulator console connection error` for no particular reason and turns out it's because we try to read emulator console auth token file [from the filesystem](https://github.com/quarkslab/AERoot/blob/f5e48b6ca31baa8b3cfa6567bb3f32d0f065ef83/aeroot/emulator.py#L66).

Not sure what's the best way to fix this, but my work-around is to mount default path of this file at the exact same path inside container:
```sh
docker run --rm \
           -v $HOME/.emulator_console_auth_token:$HOME/.emulator_console_auth_token \
           aeroot --host host.docker.internal daemon
```

Hope it will help someone.

Cheers

**Comment by Ha0ris** [comment]
Thank you for your feedback. I will try to review #48 as soon as possible.

**Comment by Ha0ris** [comment]
Just verified and merged your PR. Thank you!
